### ISSUE TITLE
RuntimeError: "bitwise_and_cpu" not implemented for 'Float' when using binary_precison & binary_recall

### ISSUE THREAD

**Issue by kidpaul94** [pytorch/torcheval#146]
### 🐛 Describe the bug

I face RuntimeError: "bitwise_and_cpu" not implemented for 'Float' when using binary_precison & binary_recall

-----------------------------------------------------------------------------------------------------------------------------------------------------

import torch
from torcheval.metrics.functional import binary_accuracy, binary_precision, binary_recall, binary_f1_score 

label = torch.FloatTensor([1., 1., 1., 1., 1., 1.])
pred =  torch.FloatTensor([0.5539, 0.5593, 0.5662, 0.4550, 0.4690, 0.4465])

acc = binary_accuracy(input=pred, target=label)
f1 = binary_f1_score(input=pred, target=label)
prec = binary_precision(input=pred, target=label)
rec = binary_recall(input=pred, target=label)

-----------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    prec = binary_precision(input=pred, target=label)
  File "/home/kidpaul/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/kidpaul/.local/lib/python3.8/site-packages/torcheval/metrics/functional/classification/precision.py", line 50, in binary_precision
    num_tp, num_fp, num_label = _binary_precision_update(input, target, threshold)
  File "/home/kidpaul/.local/lib/python3.8/site-packages/torcheval/metrics/functional/classification/precision.py", line 228, in _binary_precision_update
    num_tp = (input & target).sum()
RuntimeError: "bitwise_and_cpu" not implemented for 'Float'

### Versions

--2023-04-22 20:23:49--  https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-22 20:23:49 ERROR 404: Not Found.

--------------------------------------------------------------------------------------------------------------------------------------------------------
Python: 3.8.10 
torch: 1.11.0+cu102
torcheval: 0.0.6

**Comment by bobakfb** [comment]
Hey thanks for flagging this @kidpaul94. Im pushing a fix

**Comment by SamGalanakis** [comment]
Hi, getting following error on latest and on torcheval-nightly==2024.7.31, seems to be related.

```
  File "/workspaces/methylation_prediction/app/mil_train.py", line 114, in calculate_metrics
    metrics_dict[task_name]["recall"] = EF.binary_recall(
                                        ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torcheval/metrics/functional/classification/recall.py", line 48, in binary_recall
    num_tp, num_true_labels = _binary_recall_update(input, target, threshold)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torcheval/metrics/functional/classification/recall.py", line 61, in _binary_recall_update
    num_tp = (input & target).sum()
              ~~~~~~^~~~~~~~
```

This is for two flat float inputs, f1,  precision etc. work fine with the exact same inputs.

**Comment by mrudorfer** [comment]
Hi, I'm also getting this same error. Installed torcheval 0.0.7 from pip, with python 3.11 / torch 2.5.0 / cuda 12.4.

Code to reproduce:
```
import torch
from torcheval.metrics import BinaryRecall

metric = BinaryRecall()
predictions = torch.Tensor([0.2, 0.3, 0.5, 0.7])
targets = torch.Tensor([1.0, 0.0, 1.0, 0.0])

metric.update(predictions, targets)
```

Result:
```
Traceback (most recent call last):
  File "scripts/test_scripty.py", line 8, in <module>
    metric.update(predictions, targets)
  File "lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/torcheval/metrics/classification/recall.py", line 93, in update
    num_tp, num_true_labels = _binary_recall_update(input, target, self.threshold)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/torcheval/metrics/functional/classification/recall.py", line 59, in _binary_recall_update
    num_tp = (input & target).sum()
              ~~~~~~^~~~~~~~
RuntimeError: "bitwise_and_cpu" not implemented for 'Float'
```

**Comment by bobakfb** [comment]
> Hi, I'm also getting this same error. Installed torcheval 0.0.7 from pip, with python 3.11 / torch 2.5.0 / cuda 12.4.
> 
> Code to reproduce:
> 
> ```
> import torch
> from torcheval.metrics import BinaryRecall
> 
> metric = BinaryRecall()
> predictions = torch.Tensor([0.2, 0.3, 0.5, 0.7])
> targets = torch.Tensor([1.0, 0.0, 1.0, 0.0])
> 
> metric.update(predictions, targets)
> ```
> 
> Result:
> 
> ```
> Traceback (most recent call last):
>   File "scripts/test_scripty.py", line 8, in <module>
>     metric.update(predictions, targets)
>   File "lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "lib/python3.11/site-packages/torcheval/metrics/classification/recall.py", line 93, in update
>     num_tp, num_true_labels = _binary_recall_update(input, target, self.threshold)
>                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "lib/python3.11/site-packages/torcheval/metrics/functional/classification/recall.py", line 59, in _binary_recall_update
>     num_tp = (input & target).sum()
>               ~~~~~~^~~~~~~~
> RuntimeError: "bitwise_and_cpu" not implemented for 'Float'
> ```

Hey can you please create a new issue for this?
